name: awesome_video_player
description: The name says it all :) Feature Rich Advanced video player for Flutter, supports DRM, Subtitles, Multi-audio/video streams, and is well maintained
issue_tracker: https://github.com/nateshmbhat/awesome_video_player/issues
repository: https://github.com/nateshmbhat/awesome_video_player
version: 1.1.0
topics:
  - video
  - videoplayer
  - drm
  - audio
  - hls
homepage: https://github.com/nateshmbhat/awesome_video_player.git
documentation: https://jhomlala.github.io/betterplayer/#/

environment:
  sdk: ">=3.1.0<4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  wakelock_plus: ^1.2.4
  path_provider: ^2.1.3
  visibility_detector: ^0.4.0+2
  flutter_widget_from_html_core: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: uz.shs.better_player_plus
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
